# Generated by Django 4.2.3 on 2023-11-22 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_userextended_following_alter_userextended_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='is_following',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
