# Generated by Django 4.2.3 on 2023-11-22 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_userextended_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
