# Generated by Django 4.2.3 on 2023-11-22 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_userextended_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='is_following',
            field=models.ManyToManyField(related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
