# Generated by Django 4.2.3 on 2023-11-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_userextended_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='is_following',
        ),
    ]
