# Generated by Django 4.2.3 on 2023-11-22 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_userextended_is_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='is_following',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
