# Generated by Django 4.2.3 on 2023-11-23 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_userextended_is_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='followers',
            field=models.ManyToManyField(related_name='followers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='following',
            field=models.ManyToManyField(related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
